# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# 防止 TUI 组件里的 *.xcassets 与您项目里面冲突。
install! 'cocoapods', :disable_input_output_paths => true
target 'JHBIMSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  
  # Pods for JHBIMSDKDemo
  
  pod 'JHBIMSDK', :path => '../'
 
end
